#ifndef ENEMY_H
#define ENEMY_H

#include "NameGenerator.h"
#include "Fighter.h"
#include <string>

class Enemy : public Fighter
{
public:
    // Constructor ---    
    Enemy(int health, int damage) 
        // The name is generated by the utility class.
        : Fighter(NameGenerator::generateName(), health, damage)
    {}
};

#endif